import base64
import io

from langchain.agents import create_agent
from langchain.chat_models import init_chat_model
from langchain_core.messages import SystemMessage, HumanMessage
from loguru import logger

from app.core.config import Config
from app.workflows.object_permanence.prompts import Prompts
from app.workflows.object_permanence.state import State, StaticAnalysis


def analyze_static_frame(state: State) -> dict:
    """
    Analyzes the static frame provided in the state and returns the result of the analysis.
    This function utilizes a configured chat model to process the static frame and produce
    structured output, encapsulating insights derived from the frame.

    :param state: The current state of the application, containing the static frame to be analyzed.
                  Assumes that `state.current_frame` contains the image data, or is `None` in which
                  case an empty dictionary is returned.
    :type state: State

    :return: A dictionary containing the results of the static frame analysis. The output includes
             structured insights generated by the static frame analysis model.
    :rtype: dict
    """
    logger.trace("Entering analyze_static_frame function")
    if state.current_frame is None:
        logger.debug("Current frame is None, returning empty dict")
        return {}

    logger.debug("Initializing chat model for static frame analysis")
    model = init_chat_model(
        model=Config.GEMINI_VISION_MODEL,
        model_provider=Config.GEMINI_PROVIDER,
        api_key=Config.GEMINI_API_KEY
    )

    logger.debug("Creating agent for static frame analysis")
    agent = create_agent(
        model=model,
        response_format=StaticAnalysis,
        system_prompt=SystemMessage(
            content=Prompts.ANALYZE_STATIC_FRAME
        ),
    )

    logger.debug("Invoking agent for static frame analysis")

    image_bytes = io.BytesIO()
    state.current_frame.save(image_bytes, format='PNG')
    image_bytes.seek(0)
    image_data = base64.b64encode(image_bytes.getvalue()).decode("utf-8")

    logger.debug(f"Image data length: {len(image_data)}")
    result = agent.invoke(
        {
            "messages": [
                HumanMessage(
                    content=[
                        {
                            "type": "text",
                            "text": Prompts.ANALYZE_STATIC_FRAME
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/png;base64,{image_data}"
                            }
                        }
                    ]
                )
            ]
        }
    )

    logger.trace("Exiting analyze_static_frame function")
    return {
        "static_analysis": result["structured_response"]
    }
